apiVersion: v1
kind: Service
metadata:
  name: powerpoint-service
spec:
  type: ClusterIP
  selector:
    app: powerpoint
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
      
